config/routes.rb
Rails.application.routes.draw do
  get 'profiles' => 'profiles#index'

  get 'profiles/:id' => 'profiles#show', as: :profile

  devise_for :users

  resources :tweets do
    resource :likes
  end
  
  resources :relationships


  root 'tweets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  WillPaginate.per_page = 10
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet 

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'


end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  

  validates :user_id, presence: true
  validates :user, presence: true
  validates :message, presence: true, length: { maximum: 140, too_long: "A tweet is 140 characters max."}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :likes
  has_many :relationships
  has_many :friends, through: :relationships

  has_many :inverse_relationships, class_name: 'Relationship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_relationships, source: :user

  validates :username, presence: true, uniqueness: true

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end

  has_attached_file :avatar,
    :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :default_url => "/images/download.png",
    :styles => {
      :thumb    => ['50x50#',  :jpg, :quality => 70],

    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',

    }
    validates_attachment :avatar,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location, :avatar) }
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html {redirect_to request.referer}
    end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html {redirect_to request.referrer}
    end

  end


  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: :show

  def index
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user_tweets = @user.tweets.order(created_at: :desc).paginate(:page => params[:page])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @friend = User.find(params[:friend_id])
    @relationship = current_user.relationships.build(friend_id: @friend.id)

    if @relationship.save
      flash[:notice] = "You're now following #{@friend.username}"
      redirect_to profile_path(@friend.id)
    else
      flash[:notice] = "Something went wrong, try again please."
      redirect_to profile_path(@friend.id)
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy
    flash[:notice] = "No longer following"
    redirect_to profile_path(current_user.id)
  end

  private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :ownership]
  before_action :check_owner, only: [:update, :edit, :destroy]

  def index
    @tweets = Tweet.order(created_at: :desc).paginate(:page => params[:page])
    @tweet = Tweet.new
  end

  def show

  end

  def edit

  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html {redirect_to tweets_url, notice: 'Tweet was updated'}
      else
        format.html { render :edit}
      end
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html {redirect_to tweets_url, notice: 'You tweeter you'}
      else
        format.html { render :new }
      end #end if
    end  #end respond to
  end # create action

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html {redirect_to tweets_url, notice: 'Eradicated!'}
    end
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end #end params method

  def check_owner
    unless current_user == @tweet.user
        redirect_to tweets_url, notice: 'You can not edit this Tweet' and return
    end
  end




end #end controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Almost-Twitter', tweets_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
    

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to fa_icon('user', text: 'My Account'), edit_user_registration_path  %></li>
        <li> <%= link_to fa_icon('users', text: 'People'), profiles_path  %></li>

        <li> <%= link_to fa_icon('sign-out', text: 'Sign Out'), destroy_user_session_path, method: :delete %> </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlmostTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>All Our Peoples</h1>
<% @users.each do |user| %>
<div class="panel panel-default">
  <div class="panel-body">
    <ul class="list-inline">
      <li><%= image_tag(user.avatar.url(:thumb), class: 'round-image-50') %></li>
      <li><strong><%= link_to user.username, profile_path(user) %></strong></li>

    </ul>

  </div>
  <div class="panel-footer">
    <ul class="list-inline">


    </ul>
  </div>
</div>





<% end %>
<%= will_paginate @users , class: 'digg_pagination'  %>

app/views/profiles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-4">
      <h3> <%= @user.name  %> </h3>
      <h5> <%= @user.username %> </h5>
      <h5> <%= @user.bio %> </h5>
      <h5><%= @user.location %></h5>
      <h5> Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

      <!-- Poeople user is following -->
      <%= @user.relationships.count %> following
      <br>

      <% @user.relationships.each do |relationship| %>
        <%= link_to relationship.friend.name, profile_path(relationship.friend) %>
        <br>
      <% end %>
        <br><br>

        <!-- followers -->
        <%= pluralize(@user.inverse_relationships.count, 'Follower') %>
        <br>
        <% @user.inverse_friends.each do |friend| %>
          <%= link_to friend.name, profile_path(friend) %>
          <br>
        <% end %>

    </div>

    <div class="col-xs-7">
      <div class="panel panel-default">
        <% @user_tweets.each do |tweet| %>
          <div class="panel-body">
              <strong><%= tweet.user.username %></strong> <small>tweeted
                <%= time_ago_in_words(tweet.created_at) %> ago</small>
                <br><br>
                <%= tweet.message %>

          </div>
        <% end %>
        <%= will_paginate @user_tweets , class: 'digg_pagination'  %>
      </div>

    </div>
</div>
  <!-- follow/unfollow -->
  <% if current_user.id != @user.id %>
    <% if current_user.friends.include?(@user) %>
      <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), method: :delete, class: 'btn btn-danger btn-sm' %>
    <% else %>
      <%= link_to "Follow", relationships_path(friend_id: @user.id), method: :post, class: 'btn btn-info btn-sm' %>
    <% end %>
  <% end %>

</div>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
  <%= link_to "Unlike", tweet_likes_path(@tweet), method: :delete , class: 'btn btn-small btn-warning'%>

<% else %>
  <%= link_to "Like", tweet_likes_path(@tweet), method: :post , class: 'btn btn-small btn-success'%>
  <br><br>
<% end %>

<%= pluralize(@tweet.likes.count, 'Like') %>
<br><br>

Liked by:
<br>
<% @tweet.likes.each do |like| %>
  <br>
  <%= like.user.username %>
  <br>
<% end %>
<br>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<!--  check for errors-->
<% if @tweet.errors.any?  %>
<div id= "error_explanation" class="">
  <h2>
    <%= pluralize(@tweet.errors.count, 'error') %> prohibited this tweet
    from being saved:
  </h2>
  <!--loop through errors  -->
  <ul>
    <% @tweet.errors.full_messages.each do |error_message| %>
    <li> <% error_message %> </li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- actual form -->
<div class="panel panel-default">
  <div class="panel-body">
    <%= f.label :message ,class: 'form-group'%> <br>
    <%= f.text_field :message ,class: 'form-control' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="panel-footer">
    <%= f.submit class: 'btn btn-default'%>
  </div>


</div>

<% end  %>

app/views/tweets/edit.html.erb
<h1>You said it and you should own it, but if you insist on revising history:</h1>

<%= render 'form' %>
<%= link_to 'See some tweets', tweets_path, class: 'btn btn-default' %>

app/views/tweets/index.html.erb
<p id='notice'><%= notice %></p>

<%= render 'form' %>

<% @tweets.each do |tweet| %>

  <div class="panel panel-default">
    <div class="panel-body">
      <ul class="list-inline">
        <li><%= image_tag(tweet.user.avatar.url(:thumb), class: 'round-image-50') %></li>
        <li><strong><%= tweet.user.username %></strong> wrote:</li>
        <li>"<%=tweet.message %>"</li>
        <li><%= time_ago_in_words(tweet.created_at)%> ago</li>
      </ul>

    </div>
    <div class="panel-footer">
      <ul class="list-inline">
        <li><span class="badge">0</span>  Comments</a></li>
        <li><span class="badge"><%= tweet.likes.count %></span>  Likes</a></li>
        <li></li>
        <li><%= link_to 'More', tweet %></li>
      </ul>
    </div>
  </div>


<% end %>
<%= will_paginate @tweets , class: 'digg_pagination'  %>

app/views/tweets/new.html.erb
<h1>Brand Spanking New Tweet!</h1>
<%= render 'form' %>
<%= link_to 'See some tweets', tweets_path, class: 'btn btn-default' %>

app/views/tweets/show.html.erb
<h1 id="notice"> <%= notice %></h1>
<p>
  <strong>Message:</strong> <%= @tweet.message %>
</p>
<p>
  <strong>User:</strong> <%= @tweet.user.username %>
</p>
<%= render 'shared/likes' %>
<%= link_to 'Edit', edit_tweet_path(@tweet), class: 'btn btn-default' %>
<%= link_to 'All The Tweets Are Belong To You', tweets_path, class: 'btn btn-default' %>